/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2abc118fd876d033dc5c03edcddd4d15)
interface __BaseEnv_Env {
	CARDS: R2Bucket;
	ASSETS: Fetcher;
	PUBLIC_ORIGIN: "https://share-preview.invalid";
	ALLOWED_ORIGINS: "https://share-preview.invalid";
	PLAY_BASE: "https://matthew75x.github.io/toadal-feast-web";
	CREATION_ENABLED: "false";
	ALLOW_PUBLIC_ALIAS: "false";
	RETENTION_DAYS: "7";
	MAX_DAILY_CREATES: "100";
	MAX_DAILY_RENDERS: "300";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "ALLOWED_ORIGINS" | "PLAY_BASE" | "CREATION_ENABLED" | "ALLOW_PUBLIC_ALIAS" | "RETENTION_DAYS" | "MAX_DAILY_CREATES" | "MAX_DAILY_RENDERS">> {}
}
declare module "*.png" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.ttf" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}
