const test=require('node:test'),assert=require('node:assert/strict');
const {Controller}=require('../../studio-project/toadal-feast-website/reference/assets/js/publisher-integration/integration-controller.js');const {create}=require('../../studio-project/toadal-feast-website/reference/assets/js/publisher-integration/game-services.js');const {attach}=require('../../studio-project/toadal-feast-website/reference/assets/js/publisher-integration/game-result-bridge.js');
const memory=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function fixture(overrides={}){const controls={maintenance:false,guestSessionsEnabled:true,accountCreationEnabled:false,cloudSaveWritesEnabled:true,leaderboardsEnabled:false,telemetryEnabled:true};const caps={gameId:'froggy_feast',effectiveEnvironment:'staging',capabilities:{accounts:true,guest_identity:true,cloud_save:true,telemetry:true,economy:true,privacy_ops:true,entitlements:true,achievements:true,leaderboards:true},effectiveControls:controls};const remote={gameId:'froggy_feast',environmentId:'staging',status:'active',config:{...controls}};const calls=[];const c=new Controller({config:{enabled:true,environment:'staging',gameId:'froggy_feast',buildId:'website-test',features:{accounts:true,cloudSync:true,telemetry:true,achievements:true,entitlements:true}},localStorage:memory(),sessionStorage:memory(),fetchImpl:async(url,opts)=>{calls.push({url,method:opts.method});if(url.includes('/capabilities'))return new Response(JSON.stringify({...caps,...overrides.caps}));if(url.includes('/config/'))return overrides.failConfig?new Response('{}',{status:503}):new Response(JSON.stringify({...remote,...overrides.remote}));if(url.endsWith('/guest'))return new Response(JSON.stringify({user:{id:'guest-test',kind:'guest'},session:{token:'disposable-test-token'}}),{status:201});return new Response('{}',{status:401});}});return{c,calls};}
test('failed remote config disables connected features and leaves local snapshot available',async()=>{const {c,calls}=fixture({failConfig:true});assert.equal((await c.probe()).ok,false);for(const f of ['accounts','guest','cloudSync','cloudWrite','telemetry','privacy'])assert.equal(c.permits(f),false);await assert.rejects(c.ensureGuest(),e=>e.code==='FEATURE_HELD');assert.equal(c.localSnapshot().ok,true);assert.equal(calls.some(x=>x.method==='POST'),false);});
test('remote controls are intersected with actual capabilities; login remains available when creation held',async()=>{const {c}=fixture({remote:{config:{maintenance:false,guestSessionsEnabled:false,accountCreationEnabled:false,cloudSaveWritesEnabled:false,telemetryEnabled:false,leaderboardsEnabled:false}}});assert.equal((await c.probe()).ok,true);assert.equal(c.permits('accounts'),true);for(const f of ['guest','registration','cloudWrite','telemetry','globalLeaderboardsSubmit'])assert.equal(c.permits(f),false);assert.equal(c.permits('cloudSync'),true);});
test('scope mismatch fails closed before identity or write',async()=>{const {c,calls}=fixture({caps:{effectiveEnvironment:'production'}});assert.equal((await c.probe()).ok,false);assert.equal(c.permits('cloudWrite'),false);assert.equal(calls.length,2);});
test('login preserves connected account when sync fails; never calls it completed',async()=>{const {c}=fixture();await c.probe();c.client.login=async()=>{c.client.setSession('disposable-login-token');return{user:{id:'account-test',kind:'account'}}};c.sync.reconcile=async()=>{throw Object.assign(new Error('network'),{code:'NETWORK_ERROR'})};const out=await c.login('test@example.invalid','not-a-real-password');assert.equal(out.account.user.id,'account-test');assert.equal(out.sync.ok,false);assert.equal(out.sync.action,'unavailable');assert.equal(c.client.token,'disposable-login-token');});
test('website facade refuses native main and invalid generic save payloads',async()=>{const {c}=fixture();await c.probe();const g=create(c);await assert.rejects(g.saves.load('main'),/dedicated/);await assert.rejects(g.saves.save('website-progression',{jeweled_candy:999},0),/valid website/);});
test('result bridge consumes the qualified completion event once and never writes local scores',async()=>{const handlers=new Map(),frame={isConnected:true},shell={getAttribute:()=> 'wicked-bites',querySelector:()=>frame},tracked=[],root={document:{querySelector:()=>shell},addEventListener:(n,h)=>handlers.set(n,h),removeEventListener:n=>handlers.delete(n),ToadalGuestProgression:{createStore:()=>{throw Error('must not write')}}},c={config:{leaderboardModes:{}},track:async(n,d)=>tracked.push({n,d}),permits:()=>false};assert.equal(attach(root,c).attached,true);assert.equal(handlers.has('message'),false);const h=handlers.get('toadal:validated-game-complete'),d={gameId:'wicked-bites',frame,source:'website-preview-session',completionId:'website-run-1',score:1234,durationMs:1000};h({detail:d});h({detail:d});h({detail:{...d,completionId:'website-run-2',score:-1}});await new Promise(r=>setImmediate(r));assert.deepEqual(tracked,[{n:'arcade_run_completed',d:{score:1234,durationMs:1000}}]);});
