from pathlib import Path
p=Path(r'C:\Users\Metarator\.codex\visualizations\2026\10\06\01a112c4-59eb-7f80-a3b5-4d5b10ea925c\game-challenge-directions.html')
s=p.read_text(encoding='utf-8')
s=s.replace('<br>',' <br>')
s=s.replace('aspect-ratio:844 / 390','aspect-ratio:16 / 10')
s=s.replace('aspect-ratio:16 / 9','aspect-ratio:16 / 10')
s=s.replace('height:100%;display:block;object-fit:contain','height:100%;display:block;object-fit:contain')
s=s.replace('display:block;width:100%;height:100%;object-fit:contain','display:block;width:100%;height:100%;object-fit:contain')
s=s.replace('.tf-puzzle-card>.tf-cta{position:relative;margin:0 25px 44px;', '.tf-puzzle-card>.tf-cta{position:absolute;left:25px;bottom:43px;margin:0;')
s=s.replace('.tf-puzzle-card>.tf-cta{margin-top:91px}', '.tf-puzzle-card>.tf-cta{margin-top:0}')
s=s.replace('.tf-puzzle-card>.tf-cta{margin:0 21px 45px}', '.tf-puzzle-card>.tf-cta{left:21px;bottom:45px;margin:0}')
s=s.replace('.tf-astro-callout{position:absolute;left:23px;bottom:85px;', '.tf-astro-callout{position:absolute;left:23px;bottom:101px;')
p.write_text(s,encoding='utf-8')
print('Updated spacing, tablet/computer proportions, and call-to-action placement.')
