import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

// Run from the repository root: node --test scripts/canonical-gully-gameplay-authority.test.mjs
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('canonical neutral Gully authority is proven and Wicked Bites source plus generated bytes match baseline', () => {
  const output = execFileSync(process.execPath, ['scripts/verify-canonical-gully-gameplay-authority.mjs', repo], { cwd: repo, encoding: 'utf8' });
  const report = JSON.parse(output.slice(0, output.indexOf('\nCANONICAL GULLY AUTHORITY')));
  assert.equal(report.neutralAsset.sha256, '177f30acff9a2a782ba3e80aa3e05f19860dddeb513f7de0955fadc0b8585cea');
  assert.deepEqual([report.neutralAsset.width, report.neutralAsset.height], [319, 319]);
  assert.equal(report.neutralAsset.archiveSource, 'characters/gully/gully-happy-canonical.png');
  assert.equal(report.neutralAsset.archiveSourceSha256, '5c06144b728acb893eca1996c83d92e771e73b27be466f2acf5aec0ffff96388');
  assert.deepEqual(report.neutralReferences, ['pages/home.json', 'pages/characters.json', 'pages/world.json', 'pages/media.json', 'content/registry.json']);
  assert.equal(report.unchangedGameplaySources.length, 6);
  assert.ok(report.unchangedGameplaySources.every((item) => item.unchanged));
  assert.deepEqual(report.errors, []);
});
